# Generated by Django 3.2.8 on 2021-12-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/mern-commerce/image/upload/v1632004028/QuickShair/noimage_e5ohnw.jpg', null=True, upload_to='news_pic/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='First Semester', max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='messege',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='First Semester', max_length=120),
        ),
        migrations.AlterField(
            model_name='news',
            name='dept',
            field=models.CharField(choices=[('Mechanical', 'Mechanical'), ('Civil ', 'Civil '), ('Electrical', 'Electrical'), ('ComputerScience', 'Computer Science'), ('Electronics&Communication', 'Electronics & Communication'), ('placement', 'Placement'), ('admission', 'Admission'), ('event', 'Event'), ('CareerDevelopmentCell', 'CareerDevelopmentCell')], default='Computer Science', max_length=100),
        ),
    ]
