# Generated by Django 3.2.8 on 2021-12-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20211211_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messege',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='person_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='person_email',
            field=models.EmailField(default='First Semester', max_length=30),
        ),
        migrations.AddField(
            model_name='contact',
            name='person_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
